services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    pull_policy: daily

  server:
    image: removingnest109/openstream:latest
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=Openstream;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      Ingestion__MusicLibraryPath: "/music"
    ports:
      - "9090:9090"
    volumes:
      - ./music:/app/music
    post_start:
      - command: chown -R 1000:1000 /app/music
        user: root
    pull_policy: daily

volumes:
  sql-data:
