services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  openstream-server:
    build:
      context: .
      dockerfile: src/Openstream.Server/Dockerfile
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Pass to wait script
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=Openstream;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      Ingestion__MusicLibraryPath: "/music"
    ports:
      - "8080:8080"
    volumes:
      - ./music:/music


volumes:
  sql-data:
